d = set() 
n = input("enter a random number : ")
d.add(int(n))
n = input("enter a random number : ")
d.add(int(n))
n = input("enter a random number : ")
d.add(int(n))
n = input("enter a random number : ")
d.add(int(n))
n = input("enter a random number : ")
d.add(int(n))
n = input("enter a random number : ")
d.add(int(n))
n = input("enter a random number : ")
d.add(int(n))
n = input("enter a random number : ")
d.add(int(n))
print("Unique numbers entered:", d)
